// Package models contains the types for schema ''.
package models

// GENERATED BY XO. DO NOT EDIT.

import "database/sql"

// SchemaMigration represents a row from 'schema_migration'.
type SchemaMigration struct {
	Version sql.NullInt64 `json:"version"` // version
}

// SchemaMigrationByVersion retrieves a row from 'schema_migration' as a SchemaMigration.
//
// Generated from index 'schema_migration_version_pkey'.
func SchemaMigrationByVersion(db XODB, version sql.NullInt64) (*SchemaMigration, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`version ` +
		`FROM schema_migration ` +
		`WHERE version = ?`

	// run query
	XOLog(sqlstr, version)
	sm := SchemaMigration{}

	err = db.QueryRow(sqlstr, version).Scan(&sm.Version)
	if err != nil {
		return nil, err
	}

	return &sm, nil
}
