[LogstreamerInput]
log_directory = "/var/log"
file_match = 'syslog\.log'

[PayloadEncoder]
append_newlines = false

[LogOutput]
message_matcher = "TRUE"
encoder = "PayloadEncoder"



[DashboardOutput]
ticker_interval = 1

[hekad]
maxprocs = 2
